[package]
name = "audio-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-table = { workspace = true }
num = { workspace = true }
num-traits = { workspace = true }

assert_approx_eq = "1.1"
more-asserts = "0.3"
smallvec = "1.15"
