[package]
name = "audio-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
num = { workspace = true }
num-traits = { workspace = true }

assert_approx_eq = "1.1.0"
more-asserts = "0.3.1"
smallvec = "1.15.1"
variant_count = "1.1.0"
