[package]
name = "eq-plotter-slint"
version = "0.1.0"
edition = "2021"

[dependencies]
app-lib = { path = "../app-lib" }
audio-lib = { path = "../audio-lib" }

slint = { version = "1.14.1" }

[build-dependencies]
slint-build = "1.14.1"
